### PR TITLE
bump libc

### PR DESCRIPTION
**Pull request by carllin**

### CODE REVIEW

**Comment by povilasb** [comment]
Cool, thx for the PR. Let me test if it works locally, travis build fails on nightly - we probably have to update rust version :)
Btw, which version are you using?

**Comment by povilasb** [comment]
Works for me on Rust 1.32.0. @canndrew what do you say if I make a PR with Rust changes to stable 1.33.0?

**Comment by carllin** [comment]
Hehe yeah currently on 1.33.0, thanks for the update!

**Comment by canndrew** [comment]
Sorry for taking so long to get back to this! I'm always happy to update to a newer stable rust if it enables something.

**Pull request merged**
